[server]
headless = true
runOnSave = true
enableCORS = false
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

[client]
toolbarMode = "minimal"

# Removed invalid config options
