[server]
headless = true # Keep true for deployment
runOnSave = true
enableCORS = false
enableXsrfProtection = true # Good default

[theme]
base = "light"
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

[client]
toolbarMode = "minimal"
